---
title: "summer4"
author: "Brenden Bready"
date: "7/10/2020"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(forcats)
library(stringr)
library(tidyr)
theme_set(theme_bw())
library(lme4)
```

```{r}
playlist <- read_csv("data/PlayList.csv") %>%
  mutate(Temperature = ifelse(Temperature == "-999", NA, Temperature))
injury <- read_csv("data/InjuryRecord.csv") 
track1 <- read_csv("data/PlayerTrackData.csv") %>%
  filter(., str_detect(PlayKey, ("39873|46074|36557|46646|43532|41145|46014|44860|44806|45962|46331|36621|44492|43505|41094|40474|39656|46587|46119|38364|45966|35611|44434|44489|44511")) == TRUE)
```

```{r}
playlist <- playlist %>%
  mutate(., Weather = str_replace_all(Weather, "(Mostly [Cc]loudy)|(Partly [Cc]loudy)|(Cloudy and cold)|(Cloudy and Cool)|(Cloudy, fog started developing in 2nd quarter)|(Party Cloudy)|(Hazy)|(Overcast)|(Clear to Cloudy)|(Cloudy with periods of rain, thunder possible. Winds shifting to WNW, 10-20 mph.)|(cloudy)|(Coudy)|(Cloudy, chance of rain)|(Mostly Cloudy)|(Sun & clouds)|(Partly Clouidy)", "Cloudy"), Weather = str_replace_all(Weather, "(Clear and [Ww]arm)|(Clear and Cool)|(Clear and [Cc]old)|(Clear Skies)|(Partly clear)|(Clear Skies)", "Clear"), Weather = str_replace_all(Weather, "(Sunny and [Ww]arm)|(Sunny and [Cc]old)|(Partly [Ss]unny)|(Mostly [Ss]unny)|(Clear and [Ss]unny)|(Sunny, Windy)|(Sunny Skies)" , "Sunny"))
playlist <- playlist %>%
  mutate(., Weather = str_replace_all(Weather, "Rain Chance 40%|Showers", "Rain"), Weather = str_replace_na(Weather, "Indoor"), Weather = str_replace_all(Weather, "Fair|Clear to Cloudy|Clear skies", "Clear"), Weather = str_replace_all(Weather, "Sunny and clear|Sunny Skies|Heat Index 95|Sunny, highs to upper 80s", "Sunny"))
playlist <- playlist %>%
  mutate(., Weather = str_replace_all(Weather, "Indoors|N[/]A Indoor|Controlled Climate", "Indoor"), Weather = str_replace_all(Weather, "Scattered Rain|Cloudy, 50% change of rain|Light Rain|Rainy|Rain shower|Cloudy, Rain|30% Chance of Rain|10% Chance of Rain", "Rain"), Weather = str_replace_all(Weather, "Mostly Cloudy|Rain likely, temps in low 40s.", "Cloudy"), Weather = str_replace_all(Weather, "Heavy lake effect snow|Cloudy, light snow accumulating 1-3", "Snow"), Weather = str_replace_all(Weather, "Cold|Clear", "Sunny")) 
playlist <- playlist %>%
  mutate(., Weather = str_replace_all(Weather, "N/A [(]Indoor[)]", "Indoor"), Weather = str_replace_all(Weather, "Snow[[:punct:]]", "Snow"))
playlist <- playlist %>%
  mutate(., StadiumType = str_replace_all(StadiumType, "(Oudoor)|(Outdoors)|Open|Ourdoor|Outdor|Outside|Cloudy|Outddors|Heinz Field", "Outdoor"), StadiumType = str_replace_all(StadiumType, "Indoors|Closed Dome|Dome|Bowl", "Indoor"), StadiumType = str_replace_all(StadiumType, "Retr. Roof-Closed|Outdoor Retr Roof-Outdoor|Retractable Roof|Retr. Roof - Closed|Retr. Roof-Outdoor|Indoor, Outdoor Roof|Indoord, open|Retr. Roof - Outdoor|Retr. Roof Closed|Indoord, Outdoor|Indoor, closed|Indoor, Roof Closed|Indoord, closed|Indoord", "Retractable"))
```



```{r}
injury <- injury %>%
  mutate(Days_Missed = ifelse(DM_M42 == "1", "42+", ifelse(DM_M28 == "1", "28-41", ifelse(DM_M7 == "1", "7-27", ifelse(DM_M1 == "1", "1-6", "<1")))), injury = "1") %>%
  select(PlayerKey, GameID, BodyPart, Surface, Days_Missed, injury)
```



```{r}
playlist <- left_join(playlist, injury, by = c("GameID", "PlayerKey")) %>%
  replace_na(., list(injury = 0))
```



```{r}
firstx <- track1 %>%
  group_by(., PlayKey) %>%
  slice(., 1) %>%
  select(x) %>%
  rename(., firstx = x)
firsty <- track1 %>%
  group_by(., PlayKey) %>%
  slice(., 1) %>%
  select(y) %>%
  rename(., firsty = y)
lastx = track1 %>%
  group_by(., PlayKey) %>%
  arrange(desc(time)) %>%
  slice(., 1) %>%
  select(x) %>%
  rename(., lastx = x)
lasty = track1 %>%
  group_by(., PlayKey) %>%
  arrange(desc(time)) %>%
  slice(., 1) %>%
  select(y) %>%
  rename(., lasty = y)
track1 <- track1 %>%
  group_by(., PlayKey) %>%
  mutate(., total_dis = sum(dis))
track1 <- right_join(track1, firstx, by = c("PlayKey"))
track1 <- right_join(track1, firsty, by = c("PlayKey"))
track1 <- right_join(track1, lastx, by = c("PlayKey"))
track1 <- right_join(track1, lasty, by = c("PlayKey"))
track1 <- track1 %>%
  mutate(., euc_dist = sqrt((firstx-lastx)^2 +(firsty-lasty)^2 ))
track1 <- track1 %>%
  mutate(., zigzag_prop = total_dis/euc_dist) %>%
  select(., -c(firstx,firsty,lastx,lasty))
```



```{r}
track1 <- inner_join(track1, playlist, by = c("PlayKey"))
```




```{r}
track1 <- track1 %>%
  mutate(., o = ifelse(PlayerDay < 200, ifelse(o > 270, abs(270-o), o+90), o))
track1 <- track1 %>%
  mutate(., dir1 = ifelse(abs(dir-o) > 180, 360-abs(dir-o), abs(dir-o)), movement = ifelse(dir1 <75, "Forward", ifelse(dir1 < 105, "Lateral", "Backward"))) %>%
  select(., -c(dir1))
```


```{r}
track1 <- track1 %>%
  group_by(PlayKey, movement) %>%
  mutate(., count = ifelse(movement == "Lateral", n(), NA))
track1 <- track1 %>%
  group_by(PlayKey) %>%
  fill(count, .direction = "updown") %>%
  mutate(., percent_lateral = (count/n())*100) %>%
  select(., -count)
```

```{r}
track1 <- track1 %>%
  distinct(PlayKey, .keep_all = TRUE) %>%
  select(-c(time, event, x, y, dir, dis, o, s, movement, total_dis, euc_dist))
```

```{r}
track1 <- track1 %>%
  mutate(injury = as.numeric(injury))
```

```{r}
track1 %>%
  ungroup(PlayKey) %>%
  distinct(., Temperature) %>%
  arrange(Temperature)
```



```{r}
mod1 <- glm(injury ~ FieldType + Temperature, data = track1, family = binomial)
summary(mod1)
```

```{r}
playlist %>%
  filter(., injury == 1)
```
























